"""
database.py -- Local SQLite database layer (Phase 1 migration).

Provides:
    - Three SQLAlchemy ORM models for the agent council data.
    - init_db()  : creates tables on first startup (idempotent).
    - get_db()   : FastAPI Dependency that yields a scoped session.

The database file (local_quant.db) is created in the same directory
as this module so the service is fully self-contained and portable.

Read-only contract: nothing in this module performs trading operations.
All writes are analytical records (signals, journal entries, market data).
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Generator

from sqlalchemy import (
    Column,
    DateTime,
    Float,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    create_engine,
    event,
    inspect,
    text,
)
from sqlalchemy.orm import Session, declarative_base, sessionmaker

# ---------------------------------------------------------------------------
# Engine setup
# ---------------------------------------------------------------------------

_DB_PATH: Path = Path(__file__).parent / "local_quant.db"
_DATABASE_URL: str = f"sqlite:///{_DB_PATH}"

# check_same_thread=False is required: SQLite default is single-thread only,
# but FastAPI routes run in a thread pool so multiple threads share the engine.
engine = create_engine(
    _DATABASE_URL,
    connect_args={"check_same_thread": False},
    echo=False,
)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

Base = declarative_base()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _utcnow() -> datetime:
    """UTC-aware current time — used as column default."""
    return datetime.now(timezone.utc)


# ---------------------------------------------------------------------------
# ORM Models
# ---------------------------------------------------------------------------

class StrategySignal(Base):
    """
    Analytical signal produced by the multi-agent council.
    One row per signal event; never mutated after insert.

    Fields:
        symbol      - trading symbol (e.g. XAUUSD)
        signal      - direction string: BUY | SELL | NEUTRAL | WAIT
        confidence  - aggregate council confidence, 0.0 - 1.0
        status      - lifecycle: PENDING | ACTIVE | EXPIRED
        timestamp   - UTC creation time (auto-set on insert)
    """

    __tablename__ = "strategy_signals"

    id         = Column(Integer, primary_key=True, autoincrement=True)
    symbol     = Column(String(20), nullable=False)
    signal     = Column(String(20), nullable=False)
    confidence = Column(Float,      nullable=False, default=0.0)
    status     = Column(String(20), nullable=False, default="PENDING")
    timestamp  = Column(DateTime(timezone=True), nullable=False, default=_utcnow)

    __table_args__ = (
        Index("ix_ss_symbol_ts", "symbol", "timestamp"),
    )

    def to_dict(self) -> dict:
        return {
            "id":         self.id,
            "symbol":     self.symbol,
            "signal":     self.signal,
            "confidence": self.confidence,
            "status":     self.status,
            "timestamp":  self.timestamp.isoformat() if self.timestamp else None,
        }


class DecisionJournal(Base):
    """
    Analytical decision log generated by the agent council.
    Stores the full context snapshot and per-agent vote breakdown.

    Fields:
        trade_id     - optional client-side decision identifier
        context      - JSON text: market context at decision time
        agents_votes - JSON text: {agent_name: {vote, reason, confidence}}
        result       - council outcome: APPROVED | REJECTED | PENDING
        timestamp    - UTC creation time (auto-set on insert)
    """

    __tablename__ = "decision_journal"

    id           = Column(Integer, primary_key=True, autoincrement=True)
    trade_id     = Column(String(50), nullable=True)
    context      = Column(Text, nullable=True)
    agents_votes = Column(Text, nullable=True)
    result       = Column(String(20), nullable=True)
    timestamp    = Column(DateTime(timezone=True), nullable=False, default=_utcnow)

    __table_args__ = (
        Index("ix_dj_trade_id",  "trade_id"),
        Index("ix_dj_timestamp", "timestamp"),
    )

    def to_dict(self) -> dict:
        return {
            "id":           self.id,
            "trade_id":     self.trade_id,
            "context":      self.context,
            "agents_votes": self.agents_votes,
            "result":       self.result,
            "timestamp":    self.timestamp.isoformat() if self.timestamp else None,
        }


class MarketData(Base):
    """
    OHLCV candle data cache for offline agent analysis.
    The composite unique constraint prevents duplicate candles per symbol/tf/time.

    Fields:
        symbol, timeframe, timestamp - composite unique key
        open_price, high_price,
        low_price, close_price       - standard OHLC prices
        tick_volume                  - MT5 tick count for the bar
    """

    __tablename__ = "market_data"

    id          = Column(Integer, primary_key=True, autoincrement=True)
    symbol      = Column(String(20), nullable=False)
    timeframe   = Column(String(5),  nullable=False)
    timestamp   = Column(DateTime(timezone=True), nullable=False)
    open_price  = Column(Float, nullable=False)
    high_price  = Column(Float, nullable=False)
    low_price   = Column(Float, nullable=False)
    close_price = Column(Float, nullable=False)
    tick_volume = Column(Integer, nullable=False, default=0)

    __table_args__ = (
        Index("ix_md_symbol_tf_ts", "symbol", "timeframe", "timestamp"),
        UniqueConstraint("symbol", "timeframe", "timestamp", name="uq_md_candle"),
    )

    def to_dict(self) -> dict:
        return {
            "id":          self.id,
            "symbol":      self.symbol,
            "timeframe":   self.timeframe,
            "timestamp":   self.timestamp.isoformat() if self.timestamp else None,
            "open":        self.open_price,
            "high":        self.high_price,
            "low":         self.low_price,
            "close":       self.close_price,
            "tick_volume": self.tick_volume,
        }


class GoldProAnalysis(Base):
    """
    Saved Gold Pro Lab analysis snapshot (XAUUSD confluence analysis).
    One row per "save snapshot" action from the Gold Pro Lab UI.

    Fields:
        symbol, timestamp, price        - context at analysis time
        signal, confluence_score        - confluence engine output
        entry_price, stop_loss,
        take_profit_1, take_profit_2,
        rr_ratio, lot_size              - trade plan suggestion
        atr, mtf_alignment              - supporting indicator values
        indicators                      - JSON text snapshot of key indicators
        outcome                         - win | loss | pending (manual follow-up)
    """

    __tablename__ = "gold_pro_analyses"

    id               = Column(Integer, primary_key=True, autoincrement=True)
    symbol           = Column(String(20), nullable=False)
    analysis_ts      = Column(DateTime(timezone=True), nullable=True)
    price            = Column(Float, nullable=True)
    signal           = Column(String(20), nullable=True)
    confluence_score = Column(Float, nullable=True)
    entry_price      = Column(Float, nullable=True)
    stop_loss        = Column(Float, nullable=True)
    take_profit_1    = Column(Float, nullable=True)
    take_profit_2    = Column(Float, nullable=True)
    rr_ratio         = Column(Float, nullable=True)
    lot_size         = Column(Float, nullable=True)
    atr              = Column(Float, nullable=True)
    mtf_alignment    = Column(Integer, nullable=True)
    indicators       = Column(Text, nullable=True)
    outcome          = Column(String(10), nullable=False, default="pending")
    timestamp        = Column(DateTime(timezone=True), nullable=False, default=_utcnow)

    __table_args__ = (
        Index("ix_gpa_symbol_ts", "symbol", "timestamp"),
    )

    def to_dict(self) -> dict:
        return {
            "_id":             self.id,
            "symbol":          self.symbol,
            "timestamp":       int(self.analysis_ts.timestamp() * 1000) if self.analysis_ts else None,
            "price":           self.price,
            "signal":          self.signal,
            "confluenceScore": self.confluence_score,
            "entryPrice":      self.entry_price,
            "stopLoss":        self.stop_loss,
            "takeProfit1":     self.take_profit_1,
            "takeProfit2":     self.take_profit_2,
            "rrRatio":         self.rr_ratio,
            "lotSize":         self.lot_size,
            "atr":             self.atr,
            "mtfAlignment":    self.mtf_alignment,
            "outcome":         self.outcome,
            "savedAt":         self.timestamp.isoformat() if self.timestamp else None,
        }


class SimulatedPosition(Base):
    """
    Simulated (paper) trade position created from the OKX crypto lab UI.

    Local-First, analysis-only record: nothing here is sent to any broker
    or execution endpoint. Status transitions (PENDING -> ACTIVE ->
    HIT_TP / HIT_SL / CLOSED_MANUAL) are set manually by the user from the
    Decision Journal to track simulated win-rate.

    Fields:
        symbol, source                  - e.g. "BTC-USDT", "okx"
        direction                        - "BUY" | "SELL"
        entry_price, stop_loss,
        take_profit, lot_size            - trade plan copied from the signal
        risk_amount, profit_amount       - estimated USD amounts at entry
        signal_strength                  - council confidence at entry (0..1)
        status                           - PENDING | ACTIVE | HIT_TP | HIT_SL | CLOSED_MANUAL
        opened_at, closed_at             - simulation timestamps (user supplied / set on close)
        notes                            - optional free-text note
    """

    __tablename__ = "simulated_positions"

    id              = Column(Integer, primary_key=True, autoincrement=True)
    symbol          = Column(String(20), nullable=False)
    source          = Column(String(10), nullable=False, default="okx")
    direction       = Column(String(4), nullable=False)
    entry_price     = Column(Float, nullable=True)
    stop_loss       = Column(Float, nullable=True)
    take_profit     = Column(Float, nullable=True)
    lot_size        = Column(Float, nullable=True)
    risk_amount     = Column(Float, nullable=True)
    profit_amount   = Column(Float, nullable=True)
    signal_strength = Column(Float, nullable=True)
    status          = Column(String(15), nullable=False, default="PENDING")
    opened_at       = Column(DateTime(timezone=True), nullable=True)
    closed_at       = Column(DateTime(timezone=True), nullable=True)
    notes           = Column(Text, nullable=True)
    timestamp       = Column(DateTime(timezone=True), nullable=False, default=_utcnow)

    __table_args__ = (
        Index("ix_sim_pos_symbol_status", "symbol", "status"),
    )

    def to_dict(self) -> dict:
        return {
            "_id":            self.id,
            "symbol":         self.symbol,
            "source":         self.source,
            "direction":      self.direction,
            "entryPrice":     self.entry_price,
            "stopLoss":       self.stop_loss,
            "takeProfit":     self.take_profit,
            "lotSize":        self.lot_size,
            "riskAmount":     self.risk_amount,
            "profitAmount":   self.profit_amount,
            "signalStrength": self.signal_strength,
            "status":         self.status,
            "openedAt":       self.opened_at.isoformat() if self.opened_at else None,
            "closedAt":       self.closed_at.isoformat() if self.closed_at else None,
            "notes":          self.notes,
            "createdAt":      self.timestamp.isoformat() if self.timestamp else None,
        }


class TripleFirewallSignal(Base):
    """
    Structured history of Triple Firewall confluence analysis runs.
    One row per CouncilEngine.analyze_market() call (approved or rejected).

    This table is additive and independent of strategy_signals /
    decision_journal -- it exists to give the frontend a queryable,
    structured view of the three firewalls (trend / volatility / momentum),
    the resulting confluence rating, and the market session at the time
    of analysis.

    Fields:
        symbol, direction       - context (direction may be NULL if rejected)
        approved, signal_strength - council outcome
        confluence_level         - NONE | WEAK | MEDIUM | STRONG
        aligned_count            - 0-3, number of aligned firewalls
        firewall_trend/_volatility/_momentum - per-firewall pass/fail
        sl, tp, atr, rr           - risk levels (NULL if unavailable)
        session_label            - Arabic label of active session(s)
        baghdad_hour             - hour of day in Baghdad time (UTC+3)
        timestamp                - UTC creation time (auto-set on insert)
    """

    __tablename__ = "triple_firewall_signals"

    id                 = Column(Integer, primary_key=True, autoincrement=True)
    symbol             = Column(String(20), nullable=False)
    direction          = Column(String(10), nullable=True)
    approved           = Column(Integer, nullable=False, default=0)  # 0/1 boolean
    signal_strength    = Column(Float, nullable=False, default=0.0)
    confluence_level   = Column(String(10), nullable=True)
    aligned_count      = Column(Integer, nullable=True)
    firewall_trend     = Column(Integer, nullable=True)  # 0/1/NULL
    firewall_volatility = Column(Integer, nullable=True)
    firewall_momentum  = Column(Integer, nullable=True)
    sl                 = Column(Float, nullable=True)
    tp                 = Column(Float, nullable=True)
    atr                = Column(Float, nullable=True)
    rr                 = Column(Float, nullable=True)
    session_label      = Column(String(100), nullable=True)
    baghdad_hour       = Column(Integer, nullable=True)
    timestamp          = Column(DateTime(timezone=True), nullable=False, default=_utcnow)

    __table_args__ = (
        Index("ix_tfs_symbol_ts", "symbol", "timestamp"),
        Index("ix_tfs_confluence", "confluence_level"),
    )

    def to_dict(self) -> dict:
        return {
            "id":               self.id,
            "symbol":           self.symbol,
            "direction":        self.direction,
            "approved":         bool(self.approved),
            "signalStrength":   self.signal_strength,
            "confluenceLevel":  self.confluence_level,
            "alignedCount":     self.aligned_count,
            "firewalls": {
                "trend":      bool(self.firewall_trend) if self.firewall_trend is not None else None,
                "volatility": bool(self.firewall_volatility) if self.firewall_volatility is not None else None,
                "momentum":   bool(self.firewall_momentum) if self.firewall_momentum is not None else None,
            },
            "sl":               self.sl,
            "tp":               self.tp,
            "atr":              self.atr,
            "rr":               self.rr,
            "sessionLabel":     self.session_label,
            "baghdadHour":      self.baghdad_hour,
            "timestamp":        self.timestamp.isoformat() if self.timestamp else None,
        }


class MT5TradeHistory(Base):
    """
    One row per fully-closed MT5 position (deals from history_deals_get
    grouped by position_id). Built and upserted by
    mt5_trade_sync.sync_mt5_trades_once().

    A row is inserted only once a position has at least one IN deal and
    at least one OUT/OUT_BY deal (i.e. it is fully or partially closed).
    Subsequent partial closes UPDATE close_price/close_time/close_volume/
    deals_count/profit/commission/swap on the same row -- open_time and
    matched_signal_id never change after first insert.

    Read-only contract: this table is populated purely from
    history_deals_get(); nothing here triggers order_send/order_close.
    """

    __tablename__ = "mt5_trade_history"

    id                          = Column(Integer, primary_key=True, autoincrement=True)
    position_id                 = Column(Integer, nullable=False, unique=True)
    symbol                      = Column(String(20), nullable=False)
    direction                   = Column(String(10), nullable=False)  # BUY | SELL
    volume                      = Column(Float, nullable=False)
    open_price                  = Column(Float, nullable=False)
    open_time                   = Column(DateTime(timezone=True), nullable=False)
    open_deal_ticket            = Column(Integer, nullable=False)
    close_price                 = Column(Float, nullable=False)
    close_time                  = Column(DateTime(timezone=True), nullable=False)
    close_deal_ticket           = Column(Integer, nullable=False)
    close_volume                = Column(Float, nullable=False, default=0.0)
    deals_count                 = Column(Integer, nullable=False, default=0)
    profit                      = Column(Float, nullable=False, default=0.0)
    commission                  = Column(Float, nullable=False, default=0.0)
    swap                        = Column(Float, nullable=False, default=0.0)
    comment                     = Column(String(255), nullable=True)
    magic                       = Column(Integer, nullable=True)
    matched_signal_id           = Column(Integer, nullable=True)
    matched_time_delta_seconds  = Column(Integer, nullable=True)
    created_at                  = Column(DateTime(timezone=True), nullable=False, default=_utcnow)
    updated_at                  = Column(DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow)

    __table_args__ = (
        Index("ix_mth_position_id", "position_id", unique=True),
        Index("ix_mth_symbol_open_time", "symbol", "open_time"),
    )

    def to_dict(self) -> dict:
        return {
            "id":                      self.id,
            "positionId":              self.position_id,
            "symbol":                  self.symbol,
            "direction":               self.direction,
            "volume":                  self.volume,
            "openPrice":               self.open_price,
            "openTime":                self.open_time.isoformat() if self.open_time else None,
            "openDealTicket":          self.open_deal_ticket,
            "closePrice":              self.close_price,
            "closeTime":               self.close_time.isoformat() if self.close_time else None,
            "closeDealTicket":         self.close_deal_ticket,
            "closeVolume":             self.close_volume,
            "dealsCount":              self.deals_count,
            "profit":                  self.profit,
            "commission":              self.commission,
            "swap":                    self.swap,
            "comment":                 self.comment,
            "magic":                   self.magic,
            "matchedSignalId":         self.matched_signal_id,
            "matchedTimeDeltaSeconds": self.matched_time_delta_seconds,
            "createdAt":               self.created_at.isoformat() if self.created_at else None,
            "updatedAt":               self.updated_at.isoformat() if self.updated_at else None,
        }


class MT5OpenPosition(Base):
    """
    Current snapshot of open MT5 positions (positions_get()).
    Upserted by ticket every sync cycle; rows for tickets no longer open
    are deleted (the position has been closed and will appear in
    mt5_trade_history once history_deals_get reflects it).

    Read-only contract: this table is populated purely from
    positions_get(); nothing here triggers order_send/order_close/order_modify.
    """

    __tablename__ = "mt5_open_positions"

    id                          = Column(Integer, primary_key=True, autoincrement=True)
    ticket                      = Column(Integer, nullable=False, unique=True)
    symbol                      = Column(String(20), nullable=False)
    direction                   = Column(String(10), nullable=False)  # BUY | SELL
    volume                      = Column(Float, nullable=False)
    open_price                  = Column(Float, nullable=False)
    open_time                   = Column(DateTime(timezone=True), nullable=False)
    current_price               = Column(Float, nullable=False)
    sl                          = Column(Float, nullable=True)
    tp                          = Column(Float, nullable=True)
    profit                      = Column(Float, nullable=False, default=0.0)
    comment                     = Column(String(255), nullable=True)
    matched_signal_id           = Column(Integer, nullable=True)
    matched_time_delta_seconds  = Column(Integer, nullable=True)
    updated_at                  = Column(DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow)

    __table_args__ = (
        Index("ix_mop_ticket", "ticket", unique=True),
        Index("ix_mop_symbol", "symbol"),
    )

    def to_dict(self) -> dict:
        return {
            "id":                      self.id,
            "ticket":                  self.ticket,
            "symbol":                  self.symbol,
            "direction":               self.direction,
            "volume":                  self.volume,
            "openPrice":               self.open_price,
            "openTime":                self.open_time.isoformat() if self.open_time else None,
            "currentPrice":            self.current_price,
            "sl":                      self.sl,
            "tp":                      self.tp,
            "profit":                  self.profit,
            "comment":                 self.comment,
            "matchedSignalId":         self.matched_signal_id,
            "matchedTimeDeltaSeconds": self.matched_time_delta_seconds,
            "updatedAt":               self.updated_at.isoformat() if self.updated_at else None,
        }


class EconomicNewsEvent(Base):
    """
    Organized semi-dynamic economic calendar event (News Radar -- Phase 1).

    Rows are generated from static NewsEventTemplate definitions in
    economic_calendar.py (no external API, no live news feed). `actual`
    always remains None until a real news source is connected in a future
    phase -- this is disclosed in the UI.

    Read-only contract: this table is populated purely by
    economic_calendar.sync_calendar_events(); nothing here triggers
    order_send/order_close/order_modify.
    """

    __tablename__ = "economic_news_events"

    id                  = Column(Integer, primary_key=True, autoincrement=True)
    source              = Column(String(50), nullable=False, default="organized_calendar")
    event_id            = Column(String(100), nullable=False, unique=True)
    title               = Column(String(255), nullable=False)
    currency            = Column(String(10), nullable=False)
    impact              = Column(String(10), nullable=False)  # high | medium | low
    event_time_utc      = Column(DateTime(timezone=True), nullable=False)
    event_time_baghdad  = Column(DateTime(timezone=True), nullable=False)
    forecast            = Column(String(50), nullable=True)
    previous            = Column(String(50), nullable=True)
    actual              = Column(String(50), nullable=True)
    affected_symbols    = Column(Text, nullable=False, default="[]")  # JSON-encoded list[str]
    status              = Column(String(20), nullable=False, default="upcoming")
    created_at          = Column(DateTime(timezone=True), nullable=False, default=_utcnow)
    updated_at          = Column(DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow)

    __table_args__ = (
        Index("ix_ene_event_id", "event_id", unique=True),
        Index("ix_ene_event_time_utc", "event_time_utc"),
        Index("ix_ene_currency", "currency"),
    )

    def to_dict(self) -> dict:
        return {
            "id":               self.id,
            "source":           self.source,
            "eventId":          self.event_id,
            "title":            self.title,
            "currency":         self.currency,
            "impact":           self.impact,
            "eventTimeUtc":     self.event_time_utc.isoformat() if self.event_time_utc else None,
            "eventTimeBaghdad": self.event_time_baghdad.isoformat() if self.event_time_baghdad else None,
            "forecast":         self.forecast,
            "previous":         self.previous,
            "actual":           self.actual,
            "affectedSymbols":  json.loads(self.affected_symbols or "[]"),
            "status":           self.status,
        }


class TelegramSubscriber(Base):
    """
    A user who has sent /start to the analytical Telegram bot and opted in
    to receive approved-signal recommendations (additive to the legacy
    single-chat alert configured via system_config.telegram_chat_id).

    Rows are never deleted: /stop sets is_active=0 so history (and the
    ability to re-subscribe with /start) is preserved.
    """

    __tablename__ = "telegram_subscribers"

    id                = Column(Integer, primary_key=True, autoincrement=True)
    telegram_user_id  = Column(String(32), nullable=False)
    chat_id           = Column(String(32), nullable=False, unique=True)
    username          = Column(String(64), nullable=True)
    first_name        = Column(String(128), nullable=True)
    last_name         = Column(String(128), nullable=True)
    is_active         = Column(Integer, nullable=False, default=1)  # 0/1 boolean
    is_blocked        = Column(Integer, nullable=False, default=0)  # 0/1 boolean
    created_at        = Column(DateTime(timezone=True), nullable=False, default=_utcnow)
    updated_at        = Column(DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow)
    last_start_at     = Column(DateTime(timezone=True), nullable=True)

    def to_dict(self) -> dict:
        return {
            "id":              self.id,
            "telegramUserId":  self.telegram_user_id,
            "chatId":          self.chat_id,
            "username":        self.username,
            "firstName":       self.first_name,
            "lastName":        self.last_name,
            "isActive":        bool(self.is_active),
            "isBlocked":       bool(self.is_blocked),
            "createdAt":       self.created_at.isoformat() if self.created_at else None,
            "updatedAt":       self.updated_at.isoformat() if self.updated_at else None,
            "lastStartAt":     self.last_start_at.isoformat() if self.last_start_at else None,
        }


class TelegramRecommendationDelivery(Base):
    """
    Audit log of recommendation broadcasts to subscribers.

    One row per (recommendation_id, chat_id) attempt. Used to avoid sending
    the same recommendation twice to the same subscriber and to record
    per-subscriber failures without affecting other subscribers.
    """

    __tablename__ = "telegram_recommendation_deliveries"

    id                 = Column(Integer, primary_key=True, autoincrement=True)
    recommendation_id  = Column(String(128), nullable=False)
    chat_id            = Column(String(32), nullable=False)
    sent_at            = Column(DateTime(timezone=True), nullable=False, default=_utcnow)
    status             = Column(String(16), nullable=False)  # "sent" | "failed"
    error_message      = Column(Text, nullable=True)

    __table_args__ = (
        Index("ix_trd_recommendation_chat", "recommendation_id", "chat_id"),
    )

    def to_dict(self) -> dict:
        return {
            "id":               self.id,
            "recommendationId": self.recommendation_id,
            "chatId":           self.chat_id,
            "sentAt":           self.sent_at.isoformat() if self.sent_at else None,
            "status":           self.status,
            "errorMessage":     self.error_message,
        }


class SystemConfig(Base):
    """
    Key-value configuration store for the analytical engine.

    Stores user-configurable parameters (indicator periods, multipliers,
    Telegram credentials) so they persist across service restarts without
    requiring environment variable changes.

    Keys (canonical set):
        ema_length       - EMA trend period        (default 200)
        rsi_length       - RSI momentum period     (default 14)
        atr_length       - ATR volatility period   (default 14)
        bb_length        - Bollinger Bands period  (default 20)
        bb_std           - Bollinger Bands std-dev (default 2.0)
        atr_sl_mult      - SL = entry +/- ATR * X  (default 1.5)
        atr_tp_mult      - TP = entry +/- ATR * X  (default 3.0)
        min_rr           - Minimum risk/reward     (default 2.0)
        telegram_bot_token - Telegram Bot token (stored, never logged in full)
        telegram_chat_id   - Telegram chat/channel id

    The key column has a unique constraint so SET semantics are supported
    via INSERT OR REPLACE (handled at the application layer).
    """

    __tablename__ = "system_config"

    id         = Column(Integer, primary_key=True, autoincrement=True)
    key        = Column(String(100), nullable=False, unique=True)
    value      = Column(Text, nullable=False)
    updated_at = Column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
    )

    def to_dict(self) -> dict:
        return {
            "id":         self.id,
            "key":        self.key,
            "value":      self.value,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }


# ---------------------------------------------------------------------------
# Public interface
# ---------------------------------------------------------------------------

def _ensure_telegram_subscriber_columns() -> None:
    """
    Base.metadata.create_all() only creates missing TABLES, not missing
    COLUMNS on tables that already exist. telegram_subscribers was created
    by an earlier stage and already has rows, so a new column added to the
    model needs an explicit ALTER TABLE here. Idempotent and additive --
    existing rows get the column's DEFAULT value, nothing is dropped.
    """
    inspector = inspect(engine)
    if "telegram_subscribers" not in inspector.get_table_names():
        return
    columns = {col["name"] for col in inspector.get_columns("telegram_subscribers")}
    if "is_blocked" not in columns:
        with engine.begin() as conn:
            conn.execute(text(
                "ALTER TABLE telegram_subscribers ADD COLUMN is_blocked INTEGER NOT NULL DEFAULT 0"
            ))


def init_db() -> None:
    """
    Create all tables that do not yet exist.
    Idempotent: safe to call on every service startup.
    Existing data is never dropped or altered.
    """
    Base.metadata.create_all(bind=engine)
    _ensure_telegram_subscriber_columns()


def get_db() -> Generator[Session, None, None]:
    """
    FastAPI Dependency -- yields a SQLAlchemy session for one request.

    Usage in an endpoint:
        def my_route(db: Session = Depends(get_db)):
            ...

    The session is always closed after the request, even on exceptions.
    """
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
