"""
database.py -- Local SQLite database layer (Phase 1 migration).

Provides:
    - Three SQLAlchemy ORM models for the agent council data.
    - init_db()  : creates tables on first startup (idempotent).
    - get_db()   : FastAPI Dependency that yields a scoped session.

The database file (local_quant.db) is created in the same directory
as this module so the service is fully self-contained and portable.

Read-only contract: nothing in this module performs trading operations.
All writes are analytical records (signals, journal entries, market data).
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Generator

from sqlalchemy import (
    Column,
    DateTime,
    Float,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    create_engine,
    event,
)
from sqlalchemy.orm import Session, declarative_base, sessionmaker

# ---------------------------------------------------------------------------
# Engine setup
# ---------------------------------------------------------------------------

_DB_PATH: Path = Path(__file__).parent / "local_quant.db"
_DATABASE_URL: str = f"sqlite:///{_DB_PATH}"

# check_same_thread=False is required: SQLite default is single-thread only,
# but FastAPI routes run in a thread pool so multiple threads share the engine.
engine = create_engine(
    _DATABASE_URL,
    connect_args={"check_same_thread": False},
    echo=False,
)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

Base = declarative_base()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _utcnow() -> datetime:
    """UTC-aware current time — used as column default."""
    return datetime.now(timezone.utc)


# ---------------------------------------------------------------------------
# ORM Models
# ---------------------------------------------------------------------------

class StrategySignal(Base):
    """
    Analytical signal produced by the multi-agent council.
    One row per signal event; never mutated after insert.

    Fields:
        symbol      - trading symbol (e.g. XAUUSD)
        signal      - direction string: BUY | SELL | NEUTRAL | WAIT
        confidence  - aggregate council confidence, 0.0 - 1.0
        status      - lifecycle: PENDING | ACTIVE | EXPIRED
        timestamp   - UTC creation time (auto-set on insert)
    """

    __tablename__ = "strategy_signals"

    id         = Column(Integer, primary_key=True, autoincrement=True)
    symbol     = Column(String(20), nullable=False)
    signal     = Column(String(20), nullable=False)
    confidence = Column(Float,      nullable=False, default=0.0)
    status     = Column(String(20), nullable=False, default="PENDING")
    timestamp  = Column(DateTime(timezone=True), nullable=False, default=_utcnow)

    __table_args__ = (
        Index("ix_ss_symbol_ts", "symbol", "timestamp"),
    )

    def to_dict(self) -> dict:
        return {
            "id":         self.id,
            "symbol":     self.symbol,
            "signal":     self.signal,
            "confidence": self.confidence,
            "status":     self.status,
            "timestamp":  self.timestamp.isoformat() if self.timestamp else None,
        }


class DecisionJournal(Base):
    """
    Analytical decision log generated by the agent council.
    Stores the full context snapshot and per-agent vote breakdown.

    Fields:
        trade_id     - optional client-side decision identifier
        context      - JSON text: market context at decision time
        agents_votes - JSON text: {agent_name: {vote, reason, confidence}}
        result       - council outcome: APPROVED | REJECTED | PENDING
        timestamp    - UTC creation time (auto-set on insert)
    """

    __tablename__ = "decision_journal"

    id           = Column(Integer, primary_key=True, autoincrement=True)
    trade_id     = Column(String(50), nullable=True)
    context      = Column(Text, nullable=True)
    agents_votes = Column(Text, nullable=True)
    result       = Column(String(20), nullable=True)
    timestamp    = Column(DateTime(timezone=True), nullable=False, default=_utcnow)

    __table_args__ = (
        Index("ix_dj_trade_id",  "trade_id"),
        Index("ix_dj_timestamp", "timestamp"),
    )

    def to_dict(self) -> dict:
        return {
            "id":           self.id,
            "trade_id":     self.trade_id,
            "context":      self.context,
            "agents_votes": self.agents_votes,
            "result":       self.result,
            "timestamp":    self.timestamp.isoformat() if self.timestamp else None,
        }


class MarketData(Base):
    """
    OHLCV candle data cache for offline agent analysis.
    The composite unique constraint prevents duplicate candles per symbol/tf/time.

    Fields:
        symbol, timeframe, timestamp - composite unique key
        open_price, high_price,
        low_price, close_price       - standard OHLC prices
        tick_volume                  - MT5 tick count for the bar
    """

    __tablename__ = "market_data"

    id          = Column(Integer, primary_key=True, autoincrement=True)
    symbol      = Column(String(20), nullable=False)
    timeframe   = Column(String(5),  nullable=False)
    timestamp   = Column(DateTime(timezone=True), nullable=False)
    open_price  = Column(Float, nullable=False)
    high_price  = Column(Float, nullable=False)
    low_price   = Column(Float, nullable=False)
    close_price = Column(Float, nullable=False)
    tick_volume = Column(Integer, nullable=False, default=0)

    __table_args__ = (
        Index("ix_md_symbol_tf_ts", "symbol", "timeframe", "timestamp"),
        UniqueConstraint("symbol", "timeframe", "timestamp", name="uq_md_candle"),
    )

    def to_dict(self) -> dict:
        return {
            "id":          self.id,
            "symbol":      self.symbol,
            "timeframe":   self.timeframe,
            "timestamp":   self.timestamp.isoformat() if self.timestamp else None,
            "open":        self.open_price,
            "high":        self.high_price,
            "low":         self.low_price,
            "close":       self.close_price,
            "tick_volume": self.tick_volume,
        }


class GoldProAnalysis(Base):
    """
    Saved Gold Pro Lab analysis snapshot (XAUUSD confluence analysis).
    One row per "save snapshot" action from the Gold Pro Lab UI.

    Fields:
        symbol, timestamp, price        - context at analysis time
        signal, confluence_score        - confluence engine output
        entry_price, stop_loss,
        take_profit_1, take_profit_2,
        rr_ratio, lot_size              - trade plan suggestion
        atr, mtf_alignment              - supporting indicator values
        indicators                      - JSON text snapshot of key indicators
        outcome                         - win | loss | pending (manual follow-up)
    """

    __tablename__ = "gold_pro_analyses"

    id               = Column(Integer, primary_key=True, autoincrement=True)
    symbol           = Column(String(20), nullable=False)
    analysis_ts      = Column(DateTime(timezone=True), nullable=True)
    price            = Column(Float, nullable=True)
    signal           = Column(String(20), nullable=True)
    confluence_score = Column(Float, nullable=True)
    entry_price      = Column(Float, nullable=True)
    stop_loss        = Column(Float, nullable=True)
    take_profit_1    = Column(Float, nullable=True)
    take_profit_2    = Column(Float, nullable=True)
    rr_ratio         = Column(Float, nullable=True)
    lot_size         = Column(Float, nullable=True)
    atr              = Column(Float, nullable=True)
    mtf_alignment    = Column(Integer, nullable=True)
    indicators       = Column(Text, nullable=True)
    outcome          = Column(String(10), nullable=False, default="pending")
    timestamp        = Column(DateTime(timezone=True), nullable=False, default=_utcnow)

    __table_args__ = (
        Index("ix_gpa_symbol_ts", "symbol", "timestamp"),
    )

    def to_dict(self) -> dict:
        return {
            "_id":             self.id,
            "symbol":          self.symbol,
            "timestamp":       int(self.analysis_ts.timestamp() * 1000) if self.analysis_ts else None,
            "price":           self.price,
            "signal":          self.signal,
            "confluenceScore": self.confluence_score,
            "entryPrice":      self.entry_price,
            "stopLoss":        self.stop_loss,
            "takeProfit1":     self.take_profit_1,
            "takeProfit2":     self.take_profit_2,
            "rrRatio":         self.rr_ratio,
            "lotSize":         self.lot_size,
            "atr":             self.atr,
            "mtfAlignment":    self.mtf_alignment,
            "outcome":         self.outcome,
            "savedAt":         self.timestamp.isoformat() if self.timestamp else None,
        }


class TripleFirewallSignal(Base):
    """
    Structured history of Triple Firewall confluence analysis runs.
    One row per CouncilEngine.analyze_market() call (approved or rejected).

    This table is additive and independent of strategy_signals /
    decision_journal -- it exists to give the frontend a queryable,
    structured view of the three firewalls (trend / volatility / momentum),
    the resulting confluence rating, and the market session at the time
    of analysis.

    Fields:
        symbol, direction       - context (direction may be NULL if rejected)
        approved, signal_strength - council outcome
        confluence_level         - NONE | WEAK | MEDIUM | STRONG
        aligned_count            - 0-3, number of aligned firewalls
        firewall_trend/_volatility/_momentum - per-firewall pass/fail
        sl, tp, atr, rr           - risk levels (NULL if unavailable)
        session_label            - Arabic label of active session(s)
        baghdad_hour             - hour of day in Baghdad time (UTC+3)
        timestamp                - UTC creation time (auto-set on insert)
    """

    __tablename__ = "triple_firewall_signals"

    id                 = Column(Integer, primary_key=True, autoincrement=True)
    symbol             = Column(String(20), nullable=False)
    direction          = Column(String(10), nullable=True)
    approved           = Column(Integer, nullable=False, default=0)  # 0/1 boolean
    signal_strength    = Column(Float, nullable=False, default=0.0)
    confluence_level   = Column(String(10), nullable=True)
    aligned_count      = Column(Integer, nullable=True)
    firewall_trend     = Column(Integer, nullable=True)  # 0/1/NULL
    firewall_volatility = Column(Integer, nullable=True)
    firewall_momentum  = Column(Integer, nullable=True)
    sl                 = Column(Float, nullable=True)
    tp                 = Column(Float, nullable=True)
    atr                = Column(Float, nullable=True)
    rr                 = Column(Float, nullable=True)
    session_label      = Column(String(100), nullable=True)
    baghdad_hour       = Column(Integer, nullable=True)
    timestamp          = Column(DateTime(timezone=True), nullable=False, default=_utcnow)

    __table_args__ = (
        Index("ix_tfs_symbol_ts", "symbol", "timestamp"),
        Index("ix_tfs_confluence", "confluence_level"),
    )

    def to_dict(self) -> dict:
        return {
            "id":               self.id,
            "symbol":           self.symbol,
            "direction":        self.direction,
            "approved":         bool(self.approved),
            "signalStrength":   self.signal_strength,
            "confluenceLevel":  self.confluence_level,
            "alignedCount":     self.aligned_count,
            "firewalls": {
                "trend":      bool(self.firewall_trend) if self.firewall_trend is not None else None,
                "volatility": bool(self.firewall_volatility) if self.firewall_volatility is not None else None,
                "momentum":   bool(self.firewall_momentum) if self.firewall_momentum is not None else None,
            },
            "sl":               self.sl,
            "tp":               self.tp,
            "atr":              self.atr,
            "rr":               self.rr,
            "sessionLabel":     self.session_label,
            "baghdadHour":      self.baghdad_hour,
            "timestamp":        self.timestamp.isoformat() if self.timestamp else None,
        }


class SystemConfig(Base):
    """
    Key-value configuration store for the analytical engine.

    Stores user-configurable parameters (indicator periods, multipliers,
    Telegram credentials) so they persist across service restarts without
    requiring environment variable changes.

    Keys (canonical set):
        ema_length       - EMA trend period        (default 200)
        rsi_length       - RSI momentum period     (default 14)
        atr_length       - ATR volatility period   (default 14)
        bb_length        - Bollinger Bands period  (default 20)
        bb_std           - Bollinger Bands std-dev (default 2.0)
        atr_sl_mult      - SL = entry +/- ATR * X  (default 1.5)
        atr_tp_mult      - TP = entry +/- ATR * X  (default 3.0)
        min_rr           - Minimum risk/reward     (default 2.0)
        telegram_bot_token - Telegram Bot token (stored, never logged in full)
        telegram_chat_id   - Telegram chat/channel id

    The key column has a unique constraint so SET semantics are supported
    via INSERT OR REPLACE (handled at the application layer).
    """

    __tablename__ = "system_config"

    id         = Column(Integer, primary_key=True, autoincrement=True)
    key        = Column(String(100), nullable=False, unique=True)
    value      = Column(Text, nullable=False)
    updated_at = Column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
    )

    def to_dict(self) -> dict:
        return {
            "id":         self.id,
            "key":        self.key,
            "value":      self.value,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }


# ---------------------------------------------------------------------------
# Public interface
# ---------------------------------------------------------------------------

def init_db() -> None:
    """
    Create all tables that do not yet exist.
    Idempotent: safe to call on every service startup.
    Existing data is never dropped or altered.
    """
    Base.metadata.create_all(bind=engine)


def get_db() -> Generator[Session, None, None]:
    """
    FastAPI Dependency -- yields a SQLAlchemy session for one request.

    Usage in an endpoint:
        def my_route(db: Session = Depends(get_db)):
            ...

    The session is always closed after the request, even on exceptions.
    """
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
