"use client";

import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import {
  BookOpen,
  CheckCircle2,
  XCircle,
  Clock,
  RefreshCw,
  ChevronDown,
  ChevronUp,
  AlertTriangle,
  Users,
  Activity,
  X,
  MessageSquareText,
  Flame,
  Award,
} from "lucide-react";
import { cn } from "@/lib/utils";

const FASTAPI_BASE = "http://127.0.0.1:8010";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface AgentVote {
  approved:   boolean;
  confidence: number;
  reason:     string;
  direction:  string | null;
}

interface JournalContext {
  symbol?:          string;
  direction?:       string | null;
  signal_strength?: number;
  sl?:              number | null;
  tp?:              number | null;
  atr?:             number | null;
}

interface JournalEntry {
  id:           number;
  trade_id:     string | null;
  context:      JournalContext;
  agents_votes: Record<string, AgentVote>;
  result:       "APPROVED" | "REJECTED" | "WAIT";
  timestamp:    string;
}

interface JournalStats {
  total:    number;
  approved: number;
  rejected: number;
  wait:     number;
}

interface JournalResponse {
  ok:          boolean;
  total_count: number;
  stats:       JournalStats;
  data:        JournalEntry[];
  count:       number;
  entries:     JournalEntry[];
}

// ---------------------------------------------------------------------------
// Simulated Crypto Journal — types
// ---------------------------------------------------------------------------

type SimulatedPositionStatus = "PENDING" | "ACTIVE" | "HIT_TP" | "HIT_SL" | "CLOSED_MANUAL";

interface SimulatedPosition {
  _id:            number;
  symbol:         string;
  source:         string;
  direction:      "BUY" | "SELL";
  entryPrice:     number | null;
  stopLoss:       number | null;
  takeProfit:     number | null;
  lotSize:        number | null;
  riskAmount:     number | null;
  profitAmount:   number | null;
  signalStrength: number | null;
  status:         SimulatedPositionStatus;
  openedAt:       string | null;
  closedAt:       string | null;
  notes:               string | null;
  technicalPostMortem: string | null;
  actionableLesson:    string | null;
  createdAt:           string | null;
  autoGenerated:       boolean;
  sourceSignalId:      number | null;
  expectedCloseAt:     string | null;
  closeReason:         string | null;
}

interface SimulatedPositionsResponse {
  ok:        boolean;
  count:     number;
  positions: SimulatedPosition[];
}

interface SimulatedStats {
  total:        number;
  wins:         number;
  losses:       number;
  open:         number;
  closedManual: number;
  winRate:      number;
}

interface SimulatedStatsResponse {
  ok:    boolean;
  stats: SimulatedStats;
}

// ---------------------------------------------------------------------------
// Real Trade Outcomes — types
// ---------------------------------------------------------------------------

interface RealMatchedSignal {
  id:                      number;
  confluenceLevel:         string | null;
  signalStrength:          number;
  sl:                      number | null;
  tp:                      number | null;
  rr:                      number | null;
  timestamp:               string | null;
  matchedTimeDeltaSeconds: number | null;
}

interface RealClosedTrade {
  id:            number;
  positionId:    number;
  symbol:        string;
  direction:     "BUY" | "SELL";
  volume:        number;
  openPrice:     number;
  openTime:      string | null;
  closePrice:    number;
  closeTime:     string | null;
  profit:        number;
  matchedSignal: RealMatchedSignal | null;
}

interface RealOpenPosition {
  id:            number;
  ticket:        number;
  symbol:        string;
  direction:     "BUY" | "SELL";
  volume:        number;
  openPrice:     number;
  openTime:      string | null;
  currentPrice:  number;
  sl:            number | null;
  tp:            number | null;
  profit:        number;
  matchedSignal: RealMatchedSignal | null;
}

interface RealClosedResponse {
  ok:     boolean;
  total:  number;
  trades: RealClosedTrade[];
  error?: string;
}

interface RealOpenResponse {
  ok:        boolean;
  total:     number;
  positions: RealOpenPosition[];
  error?:    string;
}

// ---------------------------------------------------------------------------
// Data fetching
// ---------------------------------------------------------------------------

async function fetchJournal(
  source: "mt5" | "okx",
  page?: number,
  result?: string,
  symbol?: string,
  direction?: string,
): Promise<JournalResponse> {
  const params = new URLSearchParams({ limit: "50", source });
  if (page) params.set("page", String(page));
  if (result) params.set("result", result);
  if (symbol) params.set("symbol", symbol);
  if (direction) params.set("direction", direction);
  const res = await fetch(`${FASTAPI_BASE}/api/journal?${params.toString()}`, {
    cache: "no-store",
  });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return res.json() as Promise<JournalResponse>;
}

async function fetchSimulatedPositions(source: "mt5" | "okx"): Promise<SimulatedPositionsResponse> {
  const res = await fetch(`/api/lab/journal/simulated-positions?limit=100&source=${source}`, {
    cache: "no-store",
  });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return res.json() as Promise<SimulatedPositionsResponse>;
}

async function fetchSimulatedStats(source: "mt5" | "okx"): Promise<SimulatedStatsResponse> {
  const res = await fetch(`/api/lab/journal/simulated-positions/stats?source=${source}`, {
    cache: "no-store",
  });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return res.json() as Promise<SimulatedStatsResponse>;
}

async function fetchRealTradesOpen(source: "mt5" | "okx"): Promise<RealOpenResponse> {
  const res = await fetch(`/api/trade-history/open?source=${source}`, { cache: "no-store" });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return res.json() as Promise<RealOpenResponse>;
}

async function fetchRealTradesClosed(source: "mt5" | "okx"): Promise<RealClosedResponse> {
  const res = await fetch(`/api/trade-history/closed?source=${source}&days=365&limit=50`, {
    cache: "no-store",
  });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return res.json() as Promise<RealClosedResponse>;
}

// ---------------------------------------------------------------------------
// Agent names (Arabic display)
// ---------------------------------------------------------------------------

const AGENT_LABELS: Record<string, string> = {
  TrendAgent:      "وكيل الاتجاه",
  MomentumAgent:   "وكيل الزخم",
  VolatilityAgent: "وكيل التقلب",
  RiskAgent:       "وكيل المخاطرة",
};

const agentLabel = (key: string) => AGENT_LABELS[key] ?? key;

// ---------------------------------------------------------------------------
// Small helpers
// ---------------------------------------------------------------------------

function formatTs(ts: string): string {
  try {
    return new Date(ts).toLocaleString("ar-SA", {
      year:   "numeric",
      month:  "2-digit",
      day:    "2-digit",
      hour:   "2-digit",
      minute: "2-digit",
      hour12: false,
    });
  } catch {
    return ts;
  }
}

function DirectionBadge({ dir }: { dir?: string | null }) {
  if (!dir) return <span className="text-muted-foreground text-xs">محايد</span>;
  if (dir === "BUY")
    return (
      <span className="rounded px-1.5 py-0.5 text-xs font-bold bg-emerald-500/15 text-emerald-300">
        شراء
      </span>
    );
  return (
    <span className="rounded px-1.5 py-0.5 text-xs font-bold bg-rose-500/15 text-rose-300">
      بيع
    </span>
  );
}

function ResultBadge({ result }: { result: "APPROVED" | "REJECTED" | "WAIT" }) {
  if (result === "APPROVED")
    return (
      <span className="inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-xs font-semibold bg-emerald-500/15 text-emerald-300 border border-emerald-500/20">
        <CheckCircle2 className="h-3 w-3" />
        مقبول
      </span>
    );
  if (result === "WAIT")
    return (
      <span className="inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-xs font-semibold bg-amber-500/15 text-amber-300 border border-amber-500/20">
        <Clock className="h-3 w-3" />
        انتظار
      </span>
    );
  return (
    <span className="inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-xs font-semibold bg-rose-500/10 text-rose-300 border border-rose-500/20">
      <XCircle className="h-3 w-3" />
      مرفوض
    </span>
  );
}

// ---------------------------------------------------------------------------
// Agent Votes Expansion Panel
// ---------------------------------------------------------------------------

function AgentVotesPanel({ votes }: { votes: Record<string, AgentVote> }) {
  const keys = Object.keys(votes);
  if (keys.length === 0)
    return (
      <p className="text-xs text-muted-foreground py-2">لا توجد بيانات تصويت</p>
    );

  return (
    <div className="grid gap-2 pt-2">
      {keys.map((key) => {
        const v = votes[key]!;
        return (
          <div
            key={key}
            className={`rounded-lg border p-3 text-sm ${
              v.approved
                ? "border-emerald-500/20 bg-emerald-500/5"
                : "border-rose-500/15 bg-rose-500/5"
            }`}
          >
            <div className="flex items-center justify-between gap-2 mb-1">
              <span className="font-medium text-foreground">{agentLabel(key)}</span>
              <div className="flex items-center gap-2">
                <span className="tabular-nums text-xs text-muted-foreground">
                  {Math.round(v.confidence * 100)}%
                </span>
                {v.approved ? (
                  <CheckCircle2 className="h-3.5 w-3.5 text-emerald-400" />
                ) : (
                  <XCircle className="h-3.5 w-3.5 text-rose-400" />
                )}
              </div>
            </div>
            <p className="text-xs text-muted-foreground leading-relaxed">
              {v.reason || "لا يوجد سبب"}
            </p>
          </div>
        );
      })}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Single Journal Row
// ---------------------------------------------------------------------------

function JournalRow({ entry }: { entry: JournalEntry }) {
  const [open, setOpen] = useState(false);
  const ctx   = entry.context;
  const votes = entry.agents_votes;

  const approvedCount = Object.values(votes).filter((v) => v.approved).length;
  const totalVotes    = Object.keys(votes).length;
  const strengthPct   =
    ctx.signal_strength != null ? Math.round(ctx.signal_strength * 100) : null;

  return (
    <div
      className={`rounded-xl border transition-colors ${
        entry.result === "APPROVED"
          ? "border-emerald-500/15 bg-emerald-500/5"
          : "border-border bg-card/50"
      }`}
    >
      {/* Header row */}
      <button
        type="button"
        onClick={() => setOpen((p) => !p)}
        className="w-full text-right px-4 py-3 flex flex-wrap items-center gap-x-4 gap-y-2"
      >
        <span className="shrink-0">
          <ResultBadge result={entry.result} />
        </span>

        <span className="font-mono text-sm font-semibold text-foreground min-w-[70px]">
          {ctx.symbol ?? "—"}
        </span>

        <DirectionBadge dir={ctx.direction} />

        {strengthPct != null && (
          <span className="tabular-nums text-xs text-muted-foreground">
            قوة: {strengthPct}%
          </span>
        )}

        {ctx.sl != null && (
          <span className="tabular-nums text-xs text-muted-foreground">
            SL: {ctx.sl.toFixed(2)}
          </span>
        )}

        {ctx.tp != null && (
          <span className="tabular-nums text-xs text-muted-foreground">
            TP: {ctx.tp.toFixed(2)}
          </span>
        )}

        <span className="text-xs text-muted-foreground mr-auto">
          {formatTs(entry.timestamp)}
        </span>

        <span className="shrink-0 text-muted-foreground">
          {open ? (
            <ChevronUp className="h-4 w-4" />
          ) : (
            <ChevronDown className="h-4 w-4" />
          )}
        </span>
      </button>

      {/* Expanded votes panel */}
      {open && (
        <div className="border-t border-border/50 px-4 pb-4">
          <div className="flex items-center gap-1.5 pt-3 pb-1 text-xs font-medium text-muted-foreground">
            <Users className="h-3.5 w-3.5" />
            <span>
              تصويتات الوكلاء ({approvedCount}/{totalVotes} موافقة)
            </span>
          </div>
          <AgentVotesPanel votes={votes} />
        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Stats Bar
// ---------------------------------------------------------------------------

function StatsBar({
  total,
  approved,
  rejected,
}: {
  total:    number;
  approved: number;
  rejected: number;
}) {
  return (
    <div className="grid grid-cols-3 gap-3">
      {[
        {
          label: "إجمالي التحليلات",
          value: total,
          icon:  Clock,
          color: "text-amber-400",
          bg:    "bg-amber-500/10 border-amber-500/20",
        },
        {
          label: "إشارات مقبولة",
          value: approved,
          icon:  CheckCircle2,
          color: "text-emerald-400",
          bg:    "bg-emerald-500/10 border-emerald-500/20",
        },
        {
          label: "تحليلات مرفوضة",
          value: rejected,
          icon:  XCircle,
          color: "text-rose-400",
          bg:    "bg-rose-500/10 border-rose-500/20",
        },
      ].map(({ label, value, icon: Icon, color, bg }) => (
        <div
          key={label}
          className={`rounded-xl border p-4 flex items-center gap-3 ${bg}`}
        >
          <Icon className={`h-5 w-5 shrink-0 ${color}`} />
          <div>
            <p className="tabular-nums text-xl font-bold text-foreground">{value}</p>
            <p className="text-xs text-muted-foreground">{label}</p>
          </div>
        </div>
      ))}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Simulated Crypto Journal — status action buttons
// ---------------------------------------------------------------------------

const SIMULATED_STATUS_LABELS: Record<SimulatedPositionStatus, string> = {
  PENDING:       "بانتظار التفعيل",
  ACTIVE:        "نشطة",
  HIT_TP:        "تحقق الهدف",
  HIT_SL:        "ضرب وقف الخسارة",
  CLOSED_MANUAL: "إغلاق يدوي",
};

const CLOSE_REASON_LABELS: Record<string, string> = {
  HIT_TP:  "تحقق الهدف (TP)",
  HIT_SL:  "ضرب وقف الخسارة (SL)",
  TIMEOUT: "إغلاق تلقائي لتجاوز المدة المتوقعة",
};

function closeReasonLabel(position: SimulatedPosition): string | null {
  if (position.closeReason) return CLOSE_REASON_LABELS[position.closeReason] ?? position.closeReason;
  if (position.status === "CLOSED_MANUAL") return "إغلاق يدوي";
  return null;
}

function SimulatedPositionActions({
  position,
  onUpdated,
}: {
  position: SimulatedPosition;
  onUpdated: () => void;
}) {
  const [pendingStatus, setPendingStatus] = useState<SimulatedPositionStatus | null>(null);
  const [showModal, setShowModal] = useState(false);
  const [technicalPostMortem, setTechnicalPostMortem] = useState("");
  const [actionableLesson, setActionableLesson] = useState("");

  const updateStatus = async (status: SimulatedPositionStatus, pm?: string, lesson?: string) => {
    setPendingStatus(status);
    try {
      const res = await fetch(
        `/api/lab/journal/simulated-positions/${position._id}/status`,
        {
          method:  "POST",
          headers: { "Content-Type": "application/json" },
          body:    JSON.stringify({
            status,
            technicalPostMortem: pm || undefined,
            actionableLesson: lesson || undefined,
          }),
        },
      );
      if (res.ok) {
        setShowModal(false);
        onUpdated();
      }
    } finally {
      setPendingStatus(null);
    }
  };

  const handleActionClick = (status: SimulatedPositionStatus) => {
    if (status === "ACTIVE") {
      updateStatus(status);
    } else {
      setPendingStatus(status);
      setShowModal(true);
    }
  };

  const busy = pendingStatus !== null && !showModal;

  return (
    <>
      <div className="flex flex-wrap items-center gap-1.5">
        {position.status === "PENDING" && (
          <button
            type="button"
            onClick={() => handleActionClick("ACTIVE")}
            disabled={busy}
            className="rounded-full border border-cyan-500/30 bg-cyan-500/10 px-2.5 py-1 text-[10px] font-bold text-cyan-300 transition-colors hover:bg-cyan-500/20 disabled:opacity-50"
          >
            تفعيل
          </button>
        )}
        <button
          type="button"
          onClick={() => handleActionClick("HIT_TP")}
          disabled={busy}
          className="rounded-full border border-emerald-500/30 bg-emerald-500/10 px-2.5 py-1 text-[10px] font-bold text-emerald-300 transition-colors hover:bg-emerald-500/20 disabled:opacity-50"
        >
          HIT TP
        </button>
        <button
          type="button"
          onClick={() => handleActionClick("HIT_SL")}
          disabled={busy}
          className="rounded-full border border-rose-500/30 bg-rose-500/10 px-2.5 py-1 text-[10px] font-bold text-rose-300 transition-colors hover:bg-rose-500/20 disabled:opacity-50"
        >
          HIT SL
        </button>
        <button
          type="button"
          onClick={() => handleActionClick("CLOSED_MANUAL")}
          disabled={busy}
          className="rounded-full border border-border/40 bg-muted/20 px-2.5 py-1 text-[10px] font-bold text-muted-foreground transition-colors hover:text-foreground disabled:opacity-50"
        >
          إغلاق يدوي
        </button>
      </div>

      {showModal && pendingStatus && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 px-4"
          onClick={() => {
            setShowModal(false);
            setPendingStatus(null);
          }}
        >
          <div
            className="w-full max-w-md rounded-2xl border border-border/40 bg-card p-5 shadow-2xl"
            onClick={(e) => e.stopPropagation()}
            dir="rtl"
          >
            <div className="mb-4 flex items-center justify-between">
              <h3 className="text-sm font-bold text-foreground">
                تشريح نتيجة الصفقة (Post-Mortem)
              </h3>
              <button
                type="button"
                onClick={() => {
                  setShowModal(false);
                  setPendingStatus(null);
                }}
                className="text-muted-foreground transition-colors hover:text-foreground"
              >
                <X className="h-4 w-4" />
              </button>
            </div>

            <div className="mb-4 rounded-lg border border-border/30 bg-card/50 p-3">
              <p className="text-xs text-muted-foreground">
                إغلاق الصفقة كـ: <span className="font-bold text-foreground">{SIMULATED_STATUS_LABELS[pendingStatus]}</span>
              </p>
              <p className="text-[10px] text-muted-foreground/70 mt-1">
                سجل الملاحظات التقنية والدروس المستفادة لبناء مرجع تعليمي (اختياري).
              </p>
              {position.autoGenerated && pendingStatus === "CLOSED_MANUAL" && (
                <p className="text-[10px] text-amber-300/80 mt-1">
                  هذه صفقة متتبعة تلقائياً من النظام — وضّح سبب الإغلاق اليدوي قبل تحقق الهدف/الوقف/انتهاء المدة المتوقعة.
                </p>
              )}
            </div>

            <div className="space-y-4">
              <div>
                <label className="mb-1 block text-xs text-muted-foreground">التحليل الفني للنتيجة (Technical Post-Mortem)</label>
                <textarea
                  value={technicalPostMortem}
                  onChange={(e) => setTechnicalPostMortem(e.target.value)}
                  rows={3}
                  placeholder={
                    position.autoGenerated && pendingStatus === "CLOSED_MANUAL"
                      ? "مثال: أُغلقت يدوياً قبل الموعد المتوقع بسبب صدور خبر مهم..."
                      : "مثال: تم ضرب الوقف بسبب خبر مفاجئ، أو السعر احترم منطقة الـ FVG..."
                  }
                  className="w-full resize-none rounded-lg border border-border/30 bg-card/50 px-3 py-2 text-xs text-foreground focus:border-amber-500/50 focus:outline-none"
                />
              </div>

              <div>
                <label className="mb-1 block text-xs text-muted-foreground">الدرس المستفاد (Actionable Lesson)</label>
                <textarea
                  value={actionableLesson}
                  onChange={(e) => setActionableLesson(e.target.value)}
                  rows={3}
                  placeholder="مثال: يجب تجنب الدخول قبل الأخبار بـ 15 دقيقة..."
                  className="w-full resize-none rounded-lg border border-border/30 bg-card/50 px-3 py-2 text-xs text-foreground focus:border-amber-500/50 focus:outline-none"
                />
              </div>
            </div>

            <div className="mt-5 flex items-center gap-2">
              <button
                type="button"
                onClick={() => updateStatus(pendingStatus, technicalPostMortem, actionableLesson)}
                disabled={busy}
                className="flex-1 rounded-lg border border-amber-500/40 bg-amber-500/10 px-3 py-2 text-xs font-bold text-amber-300 transition-colors hover:bg-amber-500/20 disabled:opacity-50"
              >
                {busy ? "جاري الإغلاق..." : "تأكيد وإغلاق الصفقة"}
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}

// ---------------------------------------------------------------------------
// Simulated Crypto Journal — single position row
// ---------------------------------------------------------------------------

function fmtPrice(val: number | null | undefined) {
  if (val == null) return null;
  return new Intl.NumberFormat("en-US", { maximumFractionDigits: 5 }).format(val);
}

function fmtMoney(val: number | null | undefined) {
  if (val == null) return null;
  return new Intl.NumberFormat("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(val);
}

function SimulatedPositionRow({
  position,
  onUpdated,
}: {
  position: SimulatedPosition;
  onUpdated: () => void;
}) {
  const isOpen = position.status === "PENDING" || position.status === "ACTIVE";
  const ts = position.openedAt ?? position.createdAt;
  const reasonLabel = closeReasonLabel(position);

  return (
    <div className="rounded-xl border border-border bg-card/50 transition-colors">
      <div className="px-4 py-3 flex flex-wrap items-center gap-x-4 gap-y-2">
        <DirectionBadge dir={position.direction} />

        <span className="font-mono text-sm font-semibold text-foreground min-w-[90px]">
          {position.symbol}
        </span>

        {position.autoGenerated && (
          <span className="rounded px-1.5 py-0.5 text-[10px] font-bold bg-indigo-500/10 text-indigo-300 border border-indigo-500/30">
            تتبع تلقائي للنظام
          </span>
        )}

        {position.entryPrice != null && (
          <span className="tabular-nums text-xs text-muted-foreground">
            دخول: {fmtPrice(position.entryPrice)}
          </span>
        )}
        {position.stopLoss != null && (
          <span className="tabular-nums text-xs text-rose-300">
            SL: {fmtPrice(position.stopLoss)}
          </span>
        )}
        {position.takeProfit != null && (
          <span className="tabular-nums text-xs text-emerald-300">
            TP: {fmtPrice(position.takeProfit)}
          </span>
        )}
        {position.lotSize != null && (
          <span className="tabular-nums text-xs text-muted-foreground">
            لوت: {fmtMoney(position.lotSize)}
          </span>
        )}
        {position.riskAmount != null && (
          <span className="tabular-nums text-xs text-rose-400">
            مخاطرة: ${fmtMoney(position.riskAmount)}
          </span>
        )}
        {position.profitAmount != null && (
          <span className="tabular-nums text-xs text-emerald-400">
            ربح متوقع: ${fmtMoney(position.profitAmount)}
          </span>
        )}

        <span className="rounded px-1.5 py-0.5 text-[10px] font-medium bg-muted/30 text-muted-foreground">
          {SIMULATED_STATUS_LABELS[position.status]}
        </span>

        {reasonLabel && (
          <span
            className={cn(
              "rounded px-1.5 py-0.5 text-[10px] font-medium",
              position.closeReason === "HIT_TP"
                ? "bg-emerald-500/10 text-emerald-300"
                : position.closeReason === "HIT_SL"
                  ? "bg-rose-500/10 text-rose-300"
                  : "bg-amber-500/10 text-amber-300"
            )}
          >
            {reasonLabel}
          </span>
        )}

        {position.openedAt && (
          <span className="text-[11px] text-muted-foreground">
            المدة: {formatDuration(position.openedAt, position.closedAt)}
          </span>
        )}

        {ts && (
          <span className="text-xs text-muted-foreground mr-auto">
            {formatTs(ts)}
          </span>
        )}

        {isOpen && (
          <div className={ts ? "" : "mr-auto"}>
            <SimulatedPositionActions position={position} onUpdated={onUpdated} />
          </div>
        )}
      </div>

      {(!isOpen && (position.technicalPostMortem || position.actionableLesson)) && (
        <div className="border-t border-border/50 bg-card/30 px-4 py-3">
          <div className="grid gap-3 sm:grid-cols-2">
            {position.technicalPostMortem && (
              <div className="rounded-lg border border-border/30 bg-card/50 p-2.5 text-xs">
                <div className="mb-1.5 flex items-center gap-1.5 text-muted-foreground">
                  <Activity className="h-3.5 w-3.5" />
                  <span className="font-semibold">التحليل الفني للنتيجة</span>
                </div>
                <p className="leading-relaxed text-foreground/80">{position.technicalPostMortem}</p>
              </div>
            )}
            {position.actionableLesson && (
              <div className="rounded-lg border border-border/30 bg-card/50 p-2.5 text-xs">
                <div className="mb-1.5 flex items-center gap-1.5 text-muted-foreground">
                  <MessageSquareText className="h-3.5 w-3.5" />
                  <span className="font-semibold">الدرس المستفاد</span>
                </div>
                <p className="leading-relaxed text-foreground/80">{position.actionableLesson}</p>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Simulated Crypto Journal — section
// ---------------------------------------------------------------------------

function SimulatedPositionsSection({ source }: { source: "mt5" | "okx" }) {
  const {
    data: posData,
    isLoading: posLoading,
    isError: posError,
    refetch: refetchPositions,
  } = useQuery<SimulatedPositionsResponse>({
    queryKey: ["simulated-positions", source],
    queryFn:  () => fetchSimulatedPositions(source),
    refetchInterval: 60_000,
    retry:    false,
    staleTime: 30_000,
  });

  const { data: statsData, refetch: refetchStats } = useQuery<SimulatedStatsResponse>({
    queryKey: ["simulated-positions-stats", source],
    queryFn:  () => fetchSimulatedStats(source),
    refetchInterval: 60_000,
    retry:    false,
    staleTime: 30_000,
  });

  const positions = posData?.positions ?? [];
  const openPositions   = positions.filter((p) => p.status === "PENDING" || p.status === "ACTIVE");
  const closedPositions = positions.filter((p) => p.status !== "PENDING" && p.status !== "ACTIVE");
  const stats = statsData?.stats;

  const handleUpdated = () => {
    refetchPositions();
    refetchStats();
  };

  if (posError) return null;

  return (
    <div className="space-y-3">
      <div className="flex items-center gap-3">
        <div className={cn("flex h-9 w-9 items-center justify-center rounded-xl border", source === "mt5" ? "bg-amber-500/15 border-amber-500/25" : "bg-cyan-500/15 border-cyan-500/25")}>
          <Activity className={cn("h-4 w-4", source === "mt5" ? "text-amber-400" : "text-cyan-400")} />
        </div>
        <div>
          <h2 className="text-base font-bold text-foreground">
            الصفقات المحاكاة — {source === "mt5" ? "الفوركس والذهب" : "الكريبتو"}
          </h2>
          <p className="text-xs text-muted-foreground">
            سجل صفقات محاكي (Paper Trades) — لا تنفيذ حقيقي — للأغراض المعلوماتية فقط
          </p>
        </div>
      </div>

      {stats && (
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          <div className="rounded-xl border border-border bg-card/50 p-3 text-center">
            <p className="tabular-nums text-lg font-bold text-foreground">{stats.total}</p>
            <p className="text-[11px] text-muted-foreground">إجمالي الصفقات</p>
          </div>
          <div className={cn("rounded-xl border p-3 text-center", source === "mt5" ? "border-amber-500/20 bg-amber-500/5" : "border-cyan-500/20 bg-cyan-500/5")}>
            <p className={cn("tabular-nums text-lg font-bold", source === "mt5" ? "text-amber-300" : "text-cyan-300")}>{stats.open}</p>
            <p className="text-[11px] text-muted-foreground">صفقات مفتوحة</p>
          </div>
          <div className="rounded-xl border border-emerald-500/20 bg-emerald-500/5 p-3 text-center">
            <p className="tabular-nums text-lg font-bold text-emerald-300">{stats.winRate}%</p>
            <p className="text-[11px] text-muted-foreground">معدل النجاح</p>
          </div>
          <div className="rounded-xl border border-border bg-card/50 p-3 text-center">
            <p className="tabular-nums text-lg font-bold text-foreground">
              {stats.wins} / {stats.losses}
            </p>
            <p className="text-[11px] text-muted-foreground">هدف / وقف خسارة</p>
          </div>
        </div>
      )}

      {posLoading ? (
        <div className="h-14 rounded-xl border border-border bg-card/50 animate-pulse" />
      ) : openPositions.length === 0 && closedPositions.length === 0 ? (
        <div className="rounded-xl border border-border bg-card/30 px-4 py-8 text-center">
          <Activity className="h-8 w-8 text-muted-foreground/30 mx-auto mb-2" />
          <p className="text-sm text-muted-foreground">
            لا توجد صفقات محاكاة بعد
          </p>
          <p className="text-xs text-muted-foreground/70 mt-1">
            استخدم زر &quot;محاكاة دخول الصفقة&quot; في الطرفية لإضافة صفقة
          </p>
        </div>
      ) : (
        <div className="space-y-2">
          {openPositions.map((p) => (
            <SimulatedPositionRow key={p._id} position={p} onUpdated={handleUpdated} />
          ))}
          {closedPositions.slice(0, 10).map((p) => (
            <SimulatedPositionRow key={p._id} position={p} onUpdated={handleUpdated} />
          ))}
        </div>
      )}
    </div>
  );
}

function SimulatedPositionsTabs() {
  const [activeTab, setActiveTab] = useState<"mt5" | "okx">("mt5");

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-2 border-b border-border/50 pb-2">
        <button
          onClick={() => setActiveTab("mt5")}
          className={cn(
            "flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-semibold transition-colors",
            activeTab === "mt5"
              ? "bg-amber-500/10 text-amber-400"
              : "text-muted-foreground hover:bg-card/50 hover:text-foreground"
          )}
        >
          <Award className="h-4 w-4" />
          الذهب والفوركس (MT5)
        </button>
        <button
          onClick={() => setActiveTab("okx")}
          className={cn(
            "flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-semibold transition-colors",
            activeTab === "okx"
              ? "bg-cyan-500/10 text-cyan-400"
              : "text-muted-foreground hover:bg-card/50 hover:text-foreground"
          )}
        >
          <Flame className="h-4 w-4" />
          الكريبتو (OKX)
        </button>
      </div>

      <SimulatedPositionsSection source={activeTab} />
    </div>
  );
}

// ---------------------------------------------------------------------------
// Real Trade Outcomes — helpers
// ---------------------------------------------------------------------------

function formatRealDate(iso: string | null): string {
  if (!iso) return "—";
  try {
    return new Date(iso).toLocaleString("ar-EG", { dateStyle: "medium", timeStyle: "short" });
  } catch {
    return iso;
  }
}

function realDirectionLabel(direction: string): string {
  return direction === "BUY" ? "شراء" : "بيع";
}

function realProfitClass(profit: number): string {
  if (profit > 0) return "text-emerald-400";
  if (profit < 0) return "text-rose-400";
  return "text-slate-400";
}

function formatDuration(openIso: string | null, closeIso: string | null): string {
  if (!openIso) return "—";
  const start = new Date(openIso).getTime();
  const end = closeIso ? new Date(closeIso).getTime() : Date.now();
  const totalMinutes = Math.max(0, Math.round((end - start) / 60_000));
  const days = Math.floor(totalMinutes / 1440);
  const hours = Math.floor((totalMinutes % 1440) / 60);
  const minutes = totalMinutes % 60;

  const parts: string[] = [];
  if (days > 0) parts.push(`${days} يوم`);
  if (hours > 0) parts.push(`${hours} ساعة`);
  if (minutes > 0 || parts.length === 0) parts.push(`${minutes} دقيقة`);
  return parts.join(" و");
}

// ---------------------------------------------------------------------------
// Real Trade Outcomes — outcome badge
// ---------------------------------------------------------------------------

function RealOutcomeBadge({ profit, isOpen }: { profit: number; isOpen: boolean }) {
  if (isOpen) {
    return (
      <span
        className={cn(
          "inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-xs font-semibold border",
          profit > 0
            ? "bg-emerald-500/10 text-emerald-300 border-emerald-500/20"
            : profit < 0
              ? "bg-rose-500/10 text-rose-300 border-rose-500/20"
              : "bg-slate-500/10 text-slate-300 border-slate-500/20"
        )}
      >
        <Activity className="h-3 w-3" />
        قيد التنفيذ
      </span>
    );
  }

  if (profit > 0)
    return (
      <span className="inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-xs font-semibold bg-emerald-500/15 text-emerald-300 border border-emerald-500/20">
        <CheckCircle2 className="h-3 w-3" />
        ربح
      </span>
    );

  if (profit < 0)
    return (
      <span className="inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-xs font-semibold bg-rose-500/10 text-rose-300 border border-rose-500/20">
        <XCircle className="h-3 w-3" />
        خسارة
      </span>
    );

  return (
    <span className="inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-xs font-semibold bg-slate-500/10 text-slate-300 border border-slate-500/20">
      تعادل
    </span>
  );
}

// ---------------------------------------------------------------------------
// Real Trade Outcomes — predicted vs actual comparison
// ---------------------------------------------------------------------------

function PredictionComparison({
  signal,
  profit,
  isOpen,
}: {
  signal: RealMatchedSignal | null;
  profit: number;
  isOpen: boolean;
}) {
  if (!signal) {
    return (
      <span className="rounded border border-slate-700 bg-slate-800 px-2 py-1 text-[11px] text-slate-400 w-fit">
        صفقة يدوية — لا يوجد تحليل نظام مطابق لها
      </span>
    );
  }

  const followedPrediction = profit >= 0;

  return (
    <div className="flex flex-col gap-1 text-[11px]">
      <span className="rounded border border-emerald-500/20 bg-emerald-500/10 px-2 py-0.5 text-emerald-400 w-fit">
        مطابقة لتحليل النظام — توافق {signal.confluenceLevel ?? "—"} (قوة {Math.round(signal.signalStrength * 100)}%)
      </span>
      <span
        className={cn(
          "rounded border px-2 py-0.5 w-fit",
          followedPrediction
            ? "border-emerald-500/20 bg-emerald-500/5 text-emerald-300"
            : "border-amber-500/20 bg-amber-500/5 text-amber-300"
        )}
      >
        {followedPrediction
          ? isOpen
            ? "السعر يتحرك حالياً في الاتجاه المتوقع"
            : "استمر السوق في الاتجاه المتوقع من النظام"
          : isOpen
            ? "السعر يتحرك حالياً عكس الاتجاه المتوقع"
            : "انعكس السوق عكس الاتجاه المتوقع من النظام"}
      </span>
      {(signal.sl != null || signal.tp != null) && (
        <span className="text-slate-500">
          الهدف المتوقع: {signal.tp ?? "—"} | الوقف المتوقع: {signal.sl ?? "—"}
        </span>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Real Trade Outcomes — trade row
// ---------------------------------------------------------------------------

function RealTradeRow({
  symbol,
  direction,
  volume,
  openTime,
  closeTime,
  profit,
  matchedSignal,
  isOpen,
}: {
  symbol: string;
  direction: string;
  volume: number;
  openTime: string | null;
  closeTime: string | null;
  profit: number;
  matchedSignal: RealMatchedSignal | null;
  isOpen: boolean;
}) {
  return (
    <div className="rounded-xl border border-border bg-card/50 px-4 py-3 flex flex-wrap items-start gap-x-4 gap-y-2">
      <div className="flex flex-col gap-1 min-w-[110px]">
        <div className="flex items-center gap-2">
          <span className="font-mono text-sm font-semibold text-foreground">{symbol}</span>
          <span
            className={cn(
              "rounded px-1.5 py-0.5 text-xs font-bold",
              direction === "BUY" ? "bg-emerald-500/15 text-emerald-300" : "bg-rose-500/15 text-rose-300"
            )}
          >
            {realDirectionLabel(direction)}
          </span>
        </div>
        <span className="text-[11px] text-muted-foreground">الحجم: {volume}</span>
      </div>

      <div className="flex flex-col gap-1 min-w-[150px]">
        <span className="text-[11px] text-muted-foreground">فتح: {formatRealDate(openTime)}</span>
        <span className="text-[11px] text-muted-foreground">
          {isOpen ? "لا تزال مفتوحة" : `إغلاق: ${formatRealDate(closeTime)}`}
        </span>
        <span className="text-[11px] text-muted-foreground">المدة: {formatDuration(openTime, closeTime)}</span>
      </div>

      <div className="flex flex-col gap-1 min-w-[90px]">
        <RealOutcomeBadge profit={profit} isOpen={isOpen} />
        <span className={cn("font-mono text-sm font-bold", realProfitClass(profit))}>{profit} USD</span>
      </div>

      <div className="flex-1 min-w-[220px]">
        <PredictionComparison signal={matchedSignal} profit={profit} isOpen={isOpen} />
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Real Trade Outcomes — section + tabs
// ---------------------------------------------------------------------------

function RealTradeOutcomesSection({ source }: { source: "mt5" | "okx" }) {
  const openQuery = useQuery<RealOpenResponse>({
    queryKey:        ["real-trades-open", source],
    queryFn:         () => fetchRealTradesOpen(source),
    refetchInterval: 60_000,
    retry:           false,
    staleTime:       30_000,
  });

  const closedQuery = useQuery<RealClosedResponse>({
    queryKey:        ["real-trades-closed", source],
    queryFn:         () => fetchRealTradesClosed(source),
    refetchInterval: 60_000,
    retry:           false,
    staleTime:       30_000,
  });

  const openPositions = openQuery.data?.positions ?? [];
  const closedTrades  = closedQuery.data?.trades ?? [];
  const isLoading     = openQuery.isLoading || closedQuery.isLoading;
  const errorMessage  =
    (openQuery.data?.ok === false ? openQuery.data.error : undefined) ??
    (closedQuery.data?.ok === false ? closedQuery.data.error : undefined);

  return (
    <div className="space-y-3">
      {errorMessage && (
        <div className="rounded-xl border border-rose-500/20 bg-rose-500/5 px-4 py-3 text-xs text-rose-300">
          ⚠️ {errorMessage}
        </div>
      )}

      {isLoading && (
        <p className="text-center text-sm text-muted-foreground py-6">جاري تحميل الصفقات...</p>
      )}

      {!isLoading && openPositions.length === 0 && closedTrades.length === 0 && !errorMessage && (
        <p className="text-center text-sm text-muted-foreground py-6">
          لا توجد صفقات حقيقية مسجّلة لهذه المنصة بعد
        </p>
      )}

      {openPositions.length > 0 && (
        <div className="space-y-2">
          <h3 className="text-xs font-semibold text-muted-foreground">المراكز المفتوحة حالياً</h3>
          {openPositions.map((p) => (
            <RealTradeRow
              key={`open-${p.id}`}
              symbol={p.symbol}
              direction={p.direction}
              volume={p.volume}
              openTime={p.openTime}
              closeTime={null}
              profit={p.profit}
              matchedSignal={p.matchedSignal}
              isOpen
            />
          ))}
        </div>
      )}

      {closedTrades.length > 0 && (
        <div className="space-y-2">
          <h3 className="text-xs font-semibold text-muted-foreground">الصفقات المغلقة (آخر سنة)</h3>
          {closedTrades.map((t) => (
            <RealTradeRow
              key={`closed-${t.id}`}
              symbol={t.symbol}
              direction={t.direction}
              volume={t.volume}
              openTime={t.openTime}
              closeTime={t.closeTime}
              profit={t.profit}
              matchedSignal={t.matchedSignal}
              isOpen={false}
            />
          ))}
        </div>
      )}
    </div>
  );
}

function RealTradeOutcomesTabs() {
  const [activeTab, setActiveTab] = useState<"mt5" | "okx">("mt5");

  return (
    <div className="space-y-4">
      <div className="flex items-start gap-2 rounded-xl border border-cyan-500/20 bg-cyan-500/5 px-4 py-3">
        <Activity className="h-4 w-4 shrink-0 text-cyan-400 mt-0.5" />
        <p className="text-xs text-cyan-200/80 leading-relaxed">
          نتائج الصفقات الحقيقية المنفّذة على الحساب — تُعرض هنا لمدة الصفقة ونتيجتها (ربح/خسارة) ومقارنتها
          بتحليل النظام الأصلي، لتعلّم النظام من الأداء الفعلي. عرض فقط — للأغراض المعلوماتية، وليس توصية مالية.
        </p>
      </div>

      <div className="flex items-center gap-2 border-b border-border/50 pb-2">
        <button
          onClick={() => setActiveTab("mt5")}
          className={cn(
            "flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-semibold transition-colors",
            activeTab === "mt5"
              ? "bg-amber-500/10 text-amber-400"
              : "text-muted-foreground hover:bg-card/50 hover:text-foreground"
          )}
        >
          <Award className="h-4 w-4" />
          الذهب والفوركس (MT5)
        </button>
        <button
          onClick={() => setActiveTab("okx")}
          className={cn(
            "flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-semibold transition-colors",
            activeTab === "okx"
              ? "bg-cyan-500/10 text-cyan-400"
              : "text-muted-foreground hover:bg-card/50 hover:text-foreground"
          )}
        >
          <Flame className="h-4 w-4" />
          الكريبتو (OKX)
        </button>
      </div>

      <RealTradeOutcomesSection source={activeTab} />
    </div>
  );
}

// ---------------------------------------------------------------------------
// Main Page
// ---------------------------------------------------------------------------

export default function DecisionJournalPage() {
  const [journalSource, setJournalSource] = useState<"mt5" | "okx">("mt5");
  const [page, setPage] = useState(1);
  const [filterResult, setFilterResult] = useState<"ALL" | "APPROVED" | "REJECTED" | "WAIT">("ALL");
  const [filterSymbol, setFilterSymbol] = useState<string>("");
  const [filterDirection, setFilterDirection] = useState<"" | "BUY" | "SELL">("");

  const handleSourceChange = (val: "mt5" | "okx") => {
    setJournalSource(val);
    setPage(1);
  };

  const handleResultChange = (val: "ALL" | "APPROVED" | "REJECTED" | "WAIT") => {
    setFilterResult(val);
    setPage(1);
  };

  const handleSymbolChange = (val: string) => {
    setFilterSymbol(val.toUpperCase());
    setPage(1);
  };

  const handleDirectionChange = (val: "" | "BUY" | "SELL") => {
    setFilterDirection(val);
    setPage(1);
  };

  const { data, isLoading, isError, refetch, isFetching } =
    useQuery<JournalResponse>({
      queryKey: ["decision-journal", journalSource, page, filterResult, filterSymbol, filterDirection],
      queryFn:  () =>
        fetchJournal(journalSource, page, filterResult === "ALL" ? undefined : filterResult, filterSymbol || undefined, filterDirection || undefined),
      refetchInterval: 60_000,
      retry:           false,
      staleTime:       30_000,
    });

  const entries = data?.data ?? data?.entries ?? [];
  const totalCount = data?.total_count ?? 0;
  const stats = data?.stats ?? { total: 0, approved: 0, rejected: 0, wait: 0 };

  return (
    <div className="min-h-screen bg-background" dir="rtl">
      <div className="mx-auto max-w-4xl px-4 py-6 space-y-6">

        {/* Header */}
        <div className="flex items-start justify-between gap-3">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-amber-500/15 border border-amber-500/25">
              <BookOpen className="h-5 w-5 text-amber-400" />
            </div>
            <div>
              <h1 className="text-xl font-bold text-foreground">
                سجل القرارات التحليلية
              </h1>
              <p className="text-xs text-muted-foreground">
                تاريخ تصويتات مجلس الوكلاء — للأغراض المعلوماتية فقط
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={() => refetch()}
            disabled={isFetching}
            className="flex items-center gap-1.5 rounded-lg border border-border px-3 py-1.5 text-xs text-muted-foreground hover:text-foreground hover:border-amber-500/30 transition-colors disabled:opacity-50"
          >
            <RefreshCw className={`h-3.5 w-3.5 ${isFetching ? "animate-spin" : ""}`} />
            تحديث
          </button>
        </div>

        {/* Info banner */}
        <div className="flex items-start gap-2 rounded-xl border border-amber-500/20 bg-amber-500/5 px-4 py-3">
          <AlertTriangle className="h-4 w-4 shrink-0 text-amber-400 mt-0.5" />
          <p className="text-xs text-amber-200/80 leading-relaxed">
            هذا السجل يعرض نتائج تحليل مجلس الوكلاء الآلي — تحليل معلوماتي فقط —
            ليس توصية مالية — القرار النهائي للإنسان دائماً.
          </p>
        </div>

        {/* Simulated Crypto & MT5 Journal */}
        <SimulatedPositionsTabs />

        {/* Real Trade Outcomes */}
        <div className="space-y-3">
          <h2 className="text-sm font-bold text-foreground flex items-center gap-2">
            <Activity className="h-4 w-4 text-cyan-400" />
            نتائج الصفقات الحقيقية — للتعلم من الأداء
          </h2>
          <RealTradeOutcomesTabs />
        </div>

        {/* Decision Journal Platform Tabs */}
        <div className="flex items-center gap-2 border-b border-border/50 pb-2">
          <button
            type="button"
            onClick={() => handleSourceChange("mt5")}
            className={cn(
              "flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-semibold transition-colors",
              journalSource === "mt5"
                ? "bg-amber-500/10 text-amber-400"
                : "text-muted-foreground hover:bg-card/50 hover:text-foreground"
            )}
          >
            <Award className="h-4 w-4" />
            الذهب والفوركس (MT5)
          </button>
          <button
            type="button"
            onClick={() => handleSourceChange("okx")}
            className={cn(
              "flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-semibold transition-colors",
              journalSource === "okx"
                ? "bg-cyan-500/10 text-cyan-400"
                : "text-muted-foreground hover:bg-card/50 hover:text-foreground"
            )}
          >
            <Flame className="h-4 w-4" />
            الكريبتو (OKX)
          </button>
        </div>

        {/* Filters */}
        <div className="flex flex-wrap gap-3">
          <select
            value={filterResult}
            onChange={(e) => handleResultChange(e.target.value as "ALL" | "APPROVED" | "REJECTED" | "WAIT")}
            className="rounded-lg border border-border bg-card px-3 py-1.5 text-sm text-foreground focus:outline-none focus:border-amber-500/50"
          >
            <option value="ALL">جميع النتائج</option>
            <option value="APPROVED">مقبولة فقط (APPROVED)</option>
            <option value="REJECTED">مرفوضة فقط (REJECTED)</option>
            <option value="WAIT">قيد الانتظار (WAIT)</option>
          </select>

          <select
            value={filterDirection}
            onChange={(e) => handleDirectionChange(e.target.value as "" | "BUY" | "SELL")}
            className="rounded-lg border border-border bg-card px-3 py-1.5 text-sm text-foreground focus:outline-none focus:border-amber-500/50"
          >
            <option value="">جميع الاتجاهات</option>
            <option value="BUY">شراء (BUY)</option>
            <option value="SELL">بيع (SELL)</option>
          </select>

          <input
            type="text"
            value={filterSymbol}
            onChange={(e) => handleSymbolChange(e.target.value)}
            placeholder="فلتر بالرمز (مثال: XAUUSD)"
            className="rounded-lg border border-border bg-card px-3 py-1.5 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:border-amber-500/50 w-48"
            maxLength={20}
          />
        </div>

        {/* Stats */}
        {!isLoading && !isError && (
          <StatsBar
            total={stats.total}
            approved={stats.approved}
            rejected={stats.rejected}
          />
        )}

        {/* Loading */}
        {isLoading && (
          <div className="space-y-3">
            {Array.from({ length: 5 }).map((_, i) => (
              <div
                key={i}
                className="h-14 rounded-xl border border-border bg-card/50 animate-pulse"
              />
            ))}
          </div>
        )}

        {/* Error */}
        {isError && (
          <div className="rounded-xl border border-rose-500/20 bg-rose-500/5 px-4 py-6 text-center">
            <XCircle className="h-8 w-8 text-rose-400 mx-auto mb-2" />
            <p className="text-sm font-medium text-rose-300">
              تعذر الاتصال بخدمة FastAPI المحلية
            </p>
            <p className="text-xs text-muted-foreground mt-1">
              تأكد من تشغيل{" "}
              <span className="font-mono">uvicorn main:app --port 8010</span>
            </p>
          </div>
        )}

        {/* Empty state */}
        {!isLoading && !isError && entries.length === 0 && (
          <div className="rounded-xl border border-border bg-card/30 px-4 py-12 text-center">
            <BookOpen className="h-10 w-10 text-muted-foreground/30 mx-auto mb-3" />
            <p className="text-sm text-muted-foreground">
              لا توجد تحليلات محفوظة بعد
            </p>
            <p className="text-xs text-muted-foreground/70 mt-1">
              ستظهر هنا بمجرد تشغيل محرك المسح في خدمة FastAPI
            </p>
          </div>
        )}

        {/* Journal entries */}
        {!isLoading && entries.length > 0 && (
          <div className="space-y-4">
            <div className="space-y-2">
              {entries.map((entry) => (
                <JournalRow key={entry.id} entry={entry} />
              ))}
            </div>

            {/* Pagination Controls */}
            <div className="flex items-center justify-between border-t border-border/50 pt-4">
              <button
                type="button"
                onClick={() => setPage((p) => Math.max(1, p - 1))}
                disabled={page === 1}
                className="rounded-lg border border-border bg-card px-4 py-2 text-sm text-foreground hover:bg-card/80 disabled:opacity-50"
              >
                الصفحة السابقة
              </button>
              <span className="text-sm text-muted-foreground">
                الصفحة {page} من {Math.max(1, Math.ceil(totalCount / 50))} (إجمالي {totalCount} قرار)
              </span>
              <button
                type="button"
                onClick={() => setPage((p) => p + 1)}
                disabled={page * 50 >= totalCount}
                className="rounded-lg border border-border bg-card px-4 py-2 text-sm text-foreground hover:bg-card/80 disabled:opacity-50"
              >
                الصفحة التالية
              </button>
            </div>
          </div>
        )}

        {/* Footer */}
        <p className="text-center text-xs text-muted-foreground/60 pb-4">
          نظام محكوم بالقواعد — Stage 14 مقفل — لا تنفيذ تداول آلي
        </p>
      </div>
    </div>
  );
}
